/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthTicketsRouteImport } from './routes/_auth.tickets'
import { Route as AuthWatchlistRouteImport } from './routes/_auth.watchlist'
import { Route as ComediansIndexRouteImport } from './routes/comedians.index'
import { Route as ComediansSlugRouteImport } from './routes/comedians.$slug'
import { Route as SpecialsIndexRouteImport } from './routes/specials.index'
import { Route as SpecialsIdRouteImport } from './routes/specials.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTicketsRoute = AuthTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWatchlistRoute = AuthWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthRoute,
} as any)
const ComediansIndexRoute = ComediansIndexRouteImport.update({
  id: '/comedians/',
  path: '/comedians/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComediansSlugRoute = ComediansSlugRouteImport.update({
  id: '/comedians/$slug',
  path: '/comedians/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialsIndexRoute = SpecialsIndexRouteImport.update({
  id: '/specials/',
  path: '/specials/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialsIdRoute = SpecialsIdRouteImport.update({
  id: '/specials/$id',
  path: '/specials/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRoute
  '/clips': typeof ClipsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRoute
  '/dashboard': typeof AuthDashboardRoute
  '/tickets': typeof AuthTicketsRoute
  '/watchlist': typeof AuthWatchlistRoute
  '/comedians/$slug': typeof ComediansSlugRoute
  '/specials/$id': typeof SpecialsIdRoute
  '/comedians/': typeof ComediansIndexRoute
  '/specials/': typeof SpecialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRoute
  '/clips': typeof ClipsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRoute
  '/dashboard': typeof AuthDashboardRoute
  '/tickets': typeof AuthTicketsRoute
  '/watchlist': typeof AuthWatchlistRoute
  '/comedians/$slug': typeof ComediansSlugRoute
  '/specials/$id': typeof SpecialsIdRoute
  '/comedians': typeof ComediansIndexRoute
  '/specials': typeof SpecialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRoute
  '/clips': typeof ClipsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/tickets': typeof AuthTicketsRoute
  '/_auth/watchlist': typeof AuthWatchlistRoute
  '/comedians/$slug': typeof ComediansSlugRoute
  '/specials/$id': typeof SpecialsIdRoute
  '/comedians/': typeof ComediansIndexRoute
  '/specials/': typeof SpecialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/artists'
    | '/clips'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/tours'
    | '/dashboard'
    | '/tickets'
    | '/watchlist'
    | '/comedians/$slug'
    | '/specials/$id'
    | '/comedians/'
    | '/specials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/artists'
    | '/clips'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/tours'
    | '/dashboard'
    | '/tickets'
    | '/watchlist'
    | '/comedians/$slug'
    | '/specials/$id'
    | '/comedians'
    | '/specials'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/artists'
    | '/clips'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/tours'
    | '/_auth/dashboard'
    | '/_auth/tickets'
    | '/_auth/watchlist'
    | '/comedians/$slug'
    | '/specials/$id'
    | '/comedians/'
    | '/specials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArtistsRoute: typeof ArtistsRoute
  ClipsRoute: typeof ClipsRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ToursRoute: typeof ToursRoute
  ComediansSlugRoute: typeof ComediansSlugRoute
  SpecialsIdRoute: typeof SpecialsIdRoute
  ComediansIndexRoute: typeof ComediansIndexRoute
  SpecialsIndexRoute: typeof SpecialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tickets': {
      id: '/_auth/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthTicketsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/watchlist': {
      id: '/_auth/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthWatchlistRouteImport
      parentRoute: typeof AuthRoute
    }
    '/comedians/': {
      id: '/comedians/'
      path: '/comedians'
      fullPath: '/comedians/'
      preLoaderRoute: typeof ComediansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comedians/$slug': {
      id: '/comedians/$slug'
      path: '/comedians/$slug'
      fullPath: '/comedians/$slug'
      preLoaderRoute: typeof ComediansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specials/': {
      id: '/specials/'
      path: '/specials'
      fullPath: '/specials/'
      preLoaderRoute: typeof SpecialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specials/$id': {
      id: '/specials/$id'
      path: '/specials/$id'
      fullPath: '/specials/$id'
      preLoaderRoute: typeof SpecialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthTicketsRoute: typeof AuthTicketsRoute
  AuthWatchlistRoute: typeof AuthWatchlistRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthTicketsRoute: AuthTicketsRoute,
  AuthWatchlistRoute: AuthWatchlistRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  ArtistsRoute: ArtistsRoute,
  ClipsRoute: ClipsRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ToursRoute: ToursRoute,
  ComediansSlugRoute: ComediansSlugRoute,
  SpecialsIdRoute: SpecialsIdRoute,
  ComediansIndexRoute: ComediansIndexRoute,
  SpecialsIndexRoute: SpecialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
